NDefines.NAI.SHIPS_PRODUCTION_BASE_COST = 25000;					-- Used by the AI to normalize IC values when picking what ship to build.
NDefines.NAI.NAVY_PREFERED_MAX_SIZE = 50;
NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0;
NDefines.NAI.SCREENS_TO_CAPITAL_RATIO = 4.5;

NDefines.NNavy.COMBAT_MIN_DURATION = 20;
NDefines.NNavy.CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 22;
NDefines.NNavy.ALL_SHIPS_ACTIVATE_TIME = 26;
NDefines.NNavy.COMBAT_CHASE_RESIGNATION_HOURS = 24;
NDefines.NNavy.ANTI_AIR_TARGETING = 1.2;
NDefines.NNavy.SUBMARINE_REVEAL_BASE_CHANCE = 16;
NDefines.NNavy.SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.05
NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.01
NDefines.NNavy.WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.04
NDefines.NNavy.SHORE_BOMBARDMENT_CAP = 0.5;
NDefines.NNavy.POSITIONING_PENALTY_FOR_SHIPS_JOINED_COMBAT_AFTER_IT_STARTS = 0.02
NDefines.NNavy.MAX_POSITIONING_PENALTY_FOR_NEWLY_JOINED_SHIPS = 0.4

NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 15.0;
NDefines.NAir.NAVAL_STRIKE_CARRIER_MULTIPLIER = 15.0;
NDefines.NAir.NAVAL_STRIKE_TARGETTING_TO_AMOUNT = 0.4;
NDefines.NAir.CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 2;

NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 2;
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 3;
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 1;
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 1;
NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.05
NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0.1
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 4;

NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MIN = 0;
NDefines.NIntel.NAVY_SHIP_COUNT_INTEL_MAX = 0.4;
NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_EXISTING_CATEGORY_TYPES = 0.01;
NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.01;
NDefines.NIntel.NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.3;
NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_SHIP_CLASSES = 0.15;
NDefines.NIntel.NAVY_MIN_INTEL_TO_SHOW_SHIP_DESIGN_DETAILS = 0.5;
