NDefines = {

NNavy = {
	HIT_PROFILE_SPEED_FACTOR = 0.3,
	COMBAT_BASE_HIT_CHANCE = 0.08,
	COMBAT_BASE_CRITICAL_CHANCE = 0.3,
	CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT = 0.9,
	CHANCE_TO_DAMAGE_PART_ON_CRITICAL_HIT_FROM_AIR = 1,
	MIN_SHIPS_FOR_HIGHER_SHIP_RATIO_PENALTY = 66,
	BEST_CAPITALS_TO_SCREENS_RATIO = 0.5,
	SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CAPITALS = 2.0,
	ESCAPE_SPEED_PER_COMBAT_DAY = 0.15,
	MAX_ESCAPE_SPEED_FROM_COMBAT_DURATION = 0.60,
	CONVOY_ATTACK_BASE_FACTOR = 0.3,
	UNIT_TRANSFER_SPOTTING_SPEED_MULT = 15,
	NAVAL_INVASION_SPOTTING_SPEED_MULT = 30,
	SPOTTING_SPEED_EFFECT_FOR_INITIAL_UNIT_TRANSFER_SPOTTING = 0.5,
	SPOTTING_SPEED_EFFECT_FOR_INITIAL_NAVAL_INVASION_SPOTTING = 0.5,
	CONVOY_EFFICIENCY_MIN_VALUE = 0,
	CONVOY_HIT_PROFILE = 95,
	NAVY_PIERCING_THRESHOLDS = { 2.0, 1.0, 0.85, 0.75, 0.7, 0.65, 0.6, 0.55, 0.5, 0.3, 0.0 },
	NAVY_PIERCING_THRESHOLD_CRITICAL_VALUES = { 3.0, 1.25, 1.0, 0.65, 0.55, 0.3, 0.15, 0.1, 0.05, 0.01, 0.0 },
	NAVY_PIERCING_THRESHOLD_DAMAGE_VALUES = { 2.0, 1.0, 0.7, 0.6, 0.45, 0.35, 0.2, 0.1, 0.05, 0.02, 0.01 },
	CONVOY_DEFENSE_MAX_REGION_TO_TASKFORCE_RATIO = 2,
	COMBAT_TORPEDO_CRITICAL_CHANCE = 0.4,
	COMBAT_MIN_DURATION = 20,
	CAPITAL_ONLY_COMBAT_ACTIVATE_TIME = 22,
	ALL_SHIPS_ACTIVATE_TIME = 30,
	COMBAT_CHASE_RESIGNATION_HOURS = 1,
	SPEED_TO_ESCAPE_SPEED = 2,
	SHIP_TO_FLEET_ANTI_AIR_RATIO  = 1.0,
	MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.66,
	NAVAL_COMBAT_AIR_LOW_AA_TARGET_SCORE = 1,
	ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.15,
	ANTI_AIR_TARGETTING_TO_CHANCE = 0.25,
	TRAINING_MAX_DAILY_COUNTRY_EXP = 2,
	SUBMARINE_REVEAL_BASE_CHANCE = 15,
	SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.1,
	WAR_SCORE_GAIN_FOR_SUNK_SHIP_MANPOWER_FACTOR = 0.01,
	WAR_SCORE_GAIN_FOR_SUNK_SHIP_PRODUCTION_COST_FACTOR = 0.04,
	SHORE_BOMBARDMENT_CAP = 0.5,
	BASE_POSITIONING = 0.5,
	RELATIVE_SURFACE_DETECTION_TO_POSITIONING_FACTOR = 0.05,
	MAX_POSITIONING_BONUS_FROM_SURFACE_DETECTION = 0.2,
	POSITIONING_PENALTY_FOR_SHIPS_JOINED_COMBAT_AFTER_IT_STARTS = 0.02,
	MAX_POSITIONING_PENALTY_FOR_NEWLY_JOINED_SHIPS = 0.2,
	HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 0.5,
	MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 3,
	MAX_CARRIER_RATIO_POSITIONING_PENALTY_FACTOR = 0.2,
	DAMAGE_PENALTY_ON_MINIMUM_POSITIONING = 0.9,
	SCREENING_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 1.25,
	AA_EFFICIENCY_PENALTY_ON_MINIMUM_POSITIONING = 0.75,
	MANPOWER_LOSS_RATIO_ON_STR_LOSS = 0.1,
	MANPOWER_LOSS_RATIO_ON_SUNK = 0.25,
	BASE_GUN_COOLDOWNS = { 1.0, 8.0, 1.0 },
	COMBAT_CRITICAL_DAMAGE_MULT = 8,
	PRIDE_OF_THE_FLEET_UNASSIGN_COST = 25,
	CONVOY_ATTACK_BASE_FACTOR = 0.3,
	EXPERIENCE_FACTOR_CONVOY_ATTACK = 0.1,
	TRAINING_DAILY_COUNTRY_EXP_FACTOR = 0.005,
	TRAINING_MAX_DAILY_COUNTRY_EXP = 1.5,
	NAVAL_TRANSFER_BASE_SPEED = 4,
	AMPHIBIOUS_INVADE_SPEED_BASE = 0.25,
	SUPREMACY_PER_SHIP_PER_MANPOWER = 0.001,
	SUPREMACY_PER_SHIP_PER_IC = 0.05,
	NAVAL_COMBAT_AIR_CARRIER_TARGET_SCALE = 1000,
	UNIT_EXPERIENCE_PER_COMBAT_HOUR = 3,
	UNIT_EXPERIENCE_SCALE = 0.8,
	BASE_CARRIER_SORTIE_EFFICIENCY = 0.4,
	CARRIER_OFFENSIVE_STANCE_SORTIE_RATIO = {0.25, 0.37, 0.50, 0.62, 0.75}
	SHIP_SUPPORT_NEED_FACTOR = 0.25,
	NAVAL_DOMINANCE_STRIKE_FORCE_MULTIREGION_DECAY = 0.1,
	NAVAL_DOMINANCE_MINES_PLANTING_BONUS = 0.1,
	NAVAL_DOMINANCE_MINES_SWEEPING_BONUS = 0.1,
	NAVAL_DOMINANCE_SHIP_RECOVERY_CHANCE = 0.05,
	NAVAL_COMBAT_PLANE_MIN_STACKING_PENALTY = 150,
	NAVAL_COMBAT_PLANE_STACKING_PENALTY_EFFECT = 0.01,
	NAVAL_COMBAT_PLANE_STACKING_PENALTY_EFFECT = 0.005
	SHIP_SILHOUETTE_VALUE_PLANES_CARRIER = 500,
	COMBAT_DAMAGE_RANDOMNESS = 0.3,
	NAVY_VISIBILITY_BONUS_ON_RETURN_FOR_REPAIR = 0.6,
	SCREEN_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.25,
	CAPITAL_RATIO_FOR_FULL_SCREENING_FOR_CONVOYS = 0.1,
	STRIKE_FORCE_ON_BASE_FUEL_COST_FACTOR = 0.0,
	AGGRESION_MULTIPLIER_FOR_COMBAT = 4,
	NAVAL_RANGE_TO_INGAME_DISTANCE = 0.18,
	AGGRESSION_SETTINGS_VALUES = {
		0,		-- do not engage
		1.0,	-- low
		1.4,	-- medium
		2.2,	-- high
		10000,	-- I am death incarnate!
	},
	GUN_HIT_PROFILES = { -- hit profiles for guns, if target ih profile is lower the gun will have lower accuracy
		75.0,	-- big guns
		105.0,	-- torpedoes
		55.0,	-- small guns
	},
	MISSION_DOMINANCE_RATIOS = {
		0.0, -- HOLD
		1.0, -- PATROL
		1.0, -- STRIKE FORCE
		0.15, -- CONVOY RAIDING
		0.25, -- CONVOY ESCORT
		0.2, -- MINES PLANTING
		0.1, -- MINES SWEEPING
		0.0, -- TRAIN
		0.0, -- RESERVE_FLEET
		0.85, -- NAVAL_INVASION_SUPPORT
	},
},

NAir = {
	COMBAT_DAMAGE_SCALE_CARRIER = 40,
	NAVAL_STRIKE_CARRIER_MULTIPLIER = 12,
	CARRIER_HOURS_DELAY_AFTER_EACH_COMBAT = 3,
	DISRUPTION_FACTOR_CARRIER = 25.0,
	NAVAL_STRIKE_DAMAGE_TO_ORG = 0.25,
	AIR_AGILITY_TO_NAVAL_STRIKE_AGILITY = 0.06,
	CAPACITY_PENALTY = 3,
},

NAI = {
	SHIPS_PRODUCTION_BASE_COST = 25000,
	NAVY_PREFERED_MAX_SIZE = 65,
	NAVAL_DOCKYARDS_SHIP_FACTOR = 2.5,
	PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0,
	PRODUCTION_WAIT_TO_FINISH_IF_EXPENSIVE = 0.02,
	CARRIER_TASKFORCE_MAX_CARRIER_COUNT = 6,
	CAPITAL_TASKFORCE_MAX_CAPITAL_COUNT = 6,
	SCREEN_TASKFORCE_MAX_SHIP_COUNT = 5,
	SCREENS_TO_CAPITAL_RATIO = 3,
	MIN_CAPITALS_FOR_CARRIER_TASKFORCE = 8,
	REPAIR_TASKFORCE_SIZE = 5,
	WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_FACTOR = 2,
	WANTED_CARRIER_PLANES_PER_CARRIER_CAPACITY_IN_PRODUCTION_FACTOR = 1.5,
	AI_WANTED_CARRIER_BASED_PLANES_FACTOR = 1.5,
	CONVOY_ESCORT_SCORE_FROM_CONVOYS = 25,
	MAIN_SHIP_RATIO_TO_SPLIT = 1.6,
	MIN_MAIN_SHIP_RATIO = 0.6,
	DESIRE_USE_XP_TO_UNLOCK_NAVAL_DOCTRINE = 1.25,
	DESIRE_USE_XP_TO_UPGRADE_NAVAL_EQUIPMENT = 1,
	DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_NAVY = 30,
	VARIANT_CREATION_XP_RESERVE_NAVY = 30,
	DEFAULT_MODULE_VARIANT_CREATION_XP_CUTOFF_AIR = 15,
	VARIANT_CREATION_XP_RESERVE_AIR = 30,
	MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MIN = 0.00,
	MAX_SCREEN_TASKFORCES_FOR_CONVOY_DEFENSE_MAX = 0.25,
	MAX_SCREEN_TASKFORCES_FOR_MINE_LAYING = 0.0,
	MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO = 0.20,
	MAX_SCREEN_TASKFORCES_FOR_MINE_SWEEPING_PRIO_MIN_MINES = 250,
	MAX_SCREEN_FORCES_FOR_INVASION_SUPPORT = 0.1,
	NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS = 0.1,
	NAVAL_BASE_RATIO_ALLOCATED_FOR_REPAIRS_IN_WAR_TIME = 0.5,
	SHIP_STR_RATIO_PUT_ON_REPAIRS = 0.6,
	MAX_ALLOWED_NAVAL_DANGER = 500,
	REGION_CONVOY_DANGER_DAILY_DECAY = 10,
	MIN_NAVAL_MISSION_PRIO_TO_ASSIGN = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		200, -- PATROL
		200, -- STRIKE FORCE
		100, -- CONVOY RAIDING
		100, -- CONVOY ESCORT
		100, -- MINES PLANTING
		100, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		100, -- NAVAL INVASION SUPPORT
	},
	HIGH_PRIO_NAVAL_MISSION_SCORES = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		10000, -- PATROL
		8000, -- STRIKE FORCE
		4000, -- CONVOY RAIDING
		1500, -- CONVOY ESCORT
		-1, -- MINES PLANTING
		300, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		3000, -- NAVAL INVASION SUPPORT
	},
	MAX_MISSION_PER_TASKFORCE = {
		0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		3, -- PATROL
		4, -- STRIKE FORCE
		2, -- CONVOY RAIDING
		3, -- CONVOY ESCORT
		2, -- MINES PLANTING
		2, -- MINES SWEEPING
		0, -- TRAIN
		0, -- RESERVE_FLEET
		6, -- NAVAL INVASION SUPPORT
	},
},

NProduction = {
	EQUIPMENT_MODULE_ADD_XP_COST = 2,
	EQUIPMENT_MODULE_REPLACE_XP_COST = 3,
	EQUIPMENT_MODULE_CONVERT_XP_COST = 1,
	EQUIPMENT_MODULE_REMOVE_XP_COST = 1,
	BASE_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.1,
	MIN_NAVAL_EQUIPMENT_CONVERSION_RESOURCE_COST_FACTOR = 0.1,
},

NIntel = {
	NAVY_SHIP_COUNT_INTEL_MIN = 0,
	NAVY_SHIP_COUNT_INTEL_MAX = 0.4,
	NAVY_MIN_INTEL_TO_SHOW_EXISTING_CATEGORY_TYPES = 0.01,
	NAVY_SHIP_TYPE_COUNT_INTEL_MIN = 0.01,
	NAVY_SHIP_TYPE_COUNT_INTEL_MAX = 0.3,
	NAVY_MIN_INTEL_TO_SHOW_SHIP_CLASSES = 0.15,
	NAVY_MIN_INTEL_TO_SHOW_SHIP_DESIGN_DETAILS = 0.5,
},

NCountry = {
	NAVY_USE_HOME_BASE_FOR_RANGE = false,
},

}